### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by ratchetchan** [DxCx/plugin.video.9anime#104]
Search all of a sudden just stopped working. No results whatsoever. Have uninstalled, reinstalled, uninstalled again, installed repo, installed from repo. Still nothing. 

Makes the add-on pretty much unusable unless one wants to go through 500 pages all the time.

Edit: can't find reliable sources even from the recent lists, either.

**Comment by DxCx** [comment]
Hey @ratchetchan are you sure you are using latest version (0.0.16) ?
Just confirmed it is working well on latest version (Search + playback)

**Comment by ratchetchan** [comment]
@DxCx I am. Just tried it again and still the same results (none). It's definitely not a connection issue because other add-ons are working fine.

**Comment by cbizzle14** [comment]
I have this exact issue. But the thing is that it only happens on regular cellular data. When I'm connected to wifi everything works perfectly.

**Comment by DxCx** [comment]
Well, ill need more info from both.. logs, kodi version, host os?

**Comment by cbizzle14** [comment]
I hope this is the log you need. I'm not sure how to get a log of just 9anime if that's even possible. I'm running kodi 17.3 and this happens on both of my devices. Samsung galaxy s7 and LG GpadF 8.0 again on wifi everything works. On cellular data search doesn't work and clicking any shows in the folders results in "can't find eliable sources" this wasn't happening three weeks ago (last time I used cell data and it was working) 

http://paste.ubuntu.com/25252747/

**Comment by DxCx** [comment]
This is the right log file but i dont see anything useful.. in this log you are able to search but not to play?
Can you check if 9anime website is working on celleolar data?

**Comment by cbizzle14** [comment]
When I search I get no results. No matter what I search. I then tried Latest. One piece clicked an episode and got couldn't find sources. Website works fine on cellular

**Comment by gaining** [comment]
It's working for me today. Then again, it didn't work 2 days ago when I tried. I'm on FTMC android 4.4. The addon works almost perfectly. The autoplay feature only plays 720p if you tell it to play the highest resolution even if 1080p exists. I'm ok with that since I can't really notice a difference between 720p and 1080p. Other than that, the addon is perfect.

**Comment by hoppler** [comment]
reason for autoplay using 720p instead of 1080p source is the faulty "sort" as it is sorting alphanumerical https://github.com/DxCx/plugin.video.9anime/blob/dceac911d6153e03d563c839aa96f314cd12b8f5/resources/lib/ui/SourcesList.py#L50

but it as to sort by context. it means to strip all non numerical characters from the sources key and then sort by number like:
```
360p
720p
1080p
```
will get 
```
360
720
1080
```
which can be cast du a numeric and then be sorted. so 1080p would be the topmost and will be used in autoplay.

**Comment by DxCx** [comment]
hey @hoppler would you like to open a PR for that?
im on vacation with the family right now and will be able to handle this only a week from now..

**Comment by LordCorellon** [comment]
I added a crude sorting method to my fork that sorts based on resolution followed by server name (reverse alphabetical), I also modified utils.py to append a p to all resolutions for consistency since my cloud returns resolutions without a p (720 vs 720p).

Like everything I'm sure there are much better ways to accomplish what I did but it provides a workaround for now and a starting point.

**Comment by hoppler** [comment]
pullrequest for sort added. removed "prefer best" because in its current version its useless as i see it. the better option would be to prefere resolution in settings like 720p and above or 720p and below or more settings.

**Comment by DxCx** [comment]
Thanks both!
will be taking care of the PRs and release a new version over the weekend 👍 🎉

**Comment by DxCx** [comment]
I've taken care of resolution sorting suggested on this ticket.
but the ticket originally opened to report searching problem.
i couldn't find any traces for searching issues, are the searching issues still relevant?

**Comment by cbizzle14** [comment]
Yes just tried. Doesn't work on cell data. Tried again when connected to wifi and it worked.

**Comment by DxCx** [comment]
@cbizzle14 let's tackle that in a new issue, can you please open one with more info?
- kodi version
- logs on wifi data
- logs on cell data
- what else is broken on cell data? (only search? more functionailty as well?
