### ISSUE TITLE
the addon is not opening on IOS

### ISSUE THREAD

**Issue by Theangelofspace15** [DxCx/plugin.video.9anime#105]
this is the log
https://ares-project.uk/logupload/log.php?id=2269752
thanks for you help

**Comment by DxCx** [comment]
hey @Theangelofspace15 
is kodi available for iphones now? cool!
anyway, it looks like this is not the only plugin that is not working, but there are alot of breaks,
this is because the module "script.module.requests" which alot of addons is the one to error.
i would recommend to open a ticket there and have some insights

**Comment by Theangelofspace15** [comment]
thanks. kodi its only available in jailbroken Iphones.

Sent from my iPhone

On Aug 9, 2017, at 10:39, Hagai Cohen <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @Theangelofspace15<https://github.com/theangelofspace15>
is kodi available for iphones now? cool!
anyway, it looks like this is not the only plugin that is not working, but there are alot of breaks,
this is because the module "script.module.requests" which alot of addons is the one to error.
i would recommend to open a ticket there and have some insights

**Comment by DxCx** [comment]
well, offically im not supporting iphones  devices as i dont have one and cannot really support it without the ability to test it.
i can try and help you fix it remotely, but i'll need your help for that.
from the original logs provided it looks like something in core kodi is broken, where you able to verify if that was the issue?

**Comment by DxCx** [comment]
Closed due to inactivity.
