### ISSUE TITLE
Search and recent sub are not working.

### ISSUE THREAD

**Issue by zenakuadevent** [DxCx/plugin.video.9anime#106]
i click recent sub and nothing showed up, and i also try searching and nothing show up either. i am up to date with the addon and everything.

**Comment by DxCx** [comment]
Hey @zenakuadevent thanks for the report, but it does work perfectly for me at the moment, i'll need more info in order to help.
is it still happens? (Maybe the server was unavailable at that time)
what kodi version are you using?
is it worked for you before and suddenly stopped?
can you provide logs?

**Comment by DxCx** [comment]
Closed due to inactivity.
