### ISSUE TITLE
SPMC

### ISSUE THREAD

**Issue by wikd** [DxCx/plugin.video.9anime#119]
Any chance could get this to work on SPMC, for now all it does is say python dependancy not met.

**Comment by DxCx** [comment]
what's SPMC?

**Comment by wikd** [comment]
Android minded fork of kodi.[http://spmc.semperpax.com/](url)

**Comment by DxCx** [comment]
hey @wikd i don't have android hence i cannot really support it.
also, it looks like this is Kodi 16.

Kodi 16 is missing some https (ssl) extention and this is the reason the addon is not avaliable there.

in order to make plugin compatible with Kodi 16 a custom server in the middle is required, which i dont have also and cannot effort the monthly expenses for.

**Comment by wikd** [comment]
Oh, ok, thanks for taking a look. Guess just have to wait until spmc updates to 17.

**Comment by deathmake317** [comment]
@wikd @DxCx  spmc has been updated to a beta branch of krypton 17.4  it does work on it
