### ISSUE TITLE
9anime plugin not working on iphone

### ISSUE THREAD

**Issue by XemnasBlood** [DxCx/plugin.video.9anime#162]
i have an iphone 10.2 jailbroken with latest kodi on it 17.6 krypton, whenever i click on 9anime it doesnt open, any other addon it works. im able to install it and everything but unable to open it, i attached the log from kodi as the error is check log for more info 
[kodi.log](https://github.com/DxCx/plugin.video.9anime/files/1504455/kodi.log)
i tried all the solutions of changing the browser to 9anime.to and everything, nothing worked , i love 9anime, and i wish i can use it on my iphone, i can use it on my tablet android 

edit... the plugin is also updated to latest version :D

**Comment by miasmaejuices** [comment]
This seems to be an old issue related to the iOS/Mac and Linux builds of Kodi.

https://trac.kodi.tv/ticket/12098

Because it was never affecting enough people, it was never followed up.  The bug report is closed for now.  You may wish to re-open it if you like.

Perhaps @DxCx can shed some more light on it.

**Comment by DxCx** [comment]
well, cannot offically support jailbroken iphone or any ios device since i dont own any jailbroken one.. will be very hard to debug & fix without one..

**Comment by DxCx** [comment]
Closed due to inactivity
