### ISSUE TITLE
search history

### ISSUE THREAD

**Issue by gitfamhub** [DxCx/plugin.video.9anime#185]
Kind of tiring typing in the name of an anime too often, how about a search history? Would be much appreciated.

Thanks

**Comment by DxCx** [comment]
Do you have a link for a repo of an addon who does that? I wonder if xbmc have a dedicated api for that or we will have to invent something

**Comment by gitfamhub** [comment]
@DxCx - Yeah, there're a few:
https://github.com/nixgates/Incursion
https://github.com/jdf76/plugin.video.youtube

ty

**Comment by ypawar159** [comment]
@gitfamhub,
You could add the anime to favourites.
That way you can open it from main kodi window. Search for the anime and open it's context menu for 'Add to favourites' option.

**Comment by ypawar159** [comment]
@DxCx,
Kindly close this issue as no reply from OP.
Favourites feature does the required job.

**Comment by DxCx** [comment]
Well, i dont mind leaving this as feature request in case someone will want to pick it up later in the future :)

**Comment by xakiru** [comment]
Hey there, this feature is usefull, indeed, I added this feature, please see the PR. #255
Thanks

**Comment by DxCx** [comment]
Thanks for the feature @xakiru i want to see that the website is stable before i merge another feature
so i'll have to delay that abit..
but thanks alot! :D

**Comment by xakiru** [comment]
Yea no worries, I felt that this is a really helpful feature, so I thought I can make it happen since I'm using this plugin too.
Basicly if you check the code you can notice that this change adds two settings vars, one for enabling/disabling the feature and the other one is used to store searchs (up to 7), So this doesn't involve interaction with the websile. But sure, take your time.
Thanks,

**Comment by DxCx** [comment]
Released in version 0.0.42 thanks to @xakiru
