### ISSUE TITLE
Duplicate episodes?

### ISSUE THREAD

**Issue by Pockyrocks47** [DxCx/plugin.video.9anime#240]
Not sure if this is the proper venue for this issue, but for the anime Darling in the Franxx, both episode 15 entries (different dates) are playing the same special episode. It should be one actual episode 15 (April 21) and one special ep with the voice actors/director (April 28). Thanks so much!

**Comment by DxCx** [comment]
on 9anime website it is playing fine?
this is just a "browser" kodi module for the https://9anime.is website..

**Comment by Pockyrocks47** [comment]
Yes, on website, ep 15 plays fine, but not on kodi add-on.

**Comment by Pockyrocks47** [comment]
Maybe the kodi add-on listing both entries as episode 15 (instead of the April 28 one as a "special" as it is on the website) is what's causing the problem?
![20180515_202733](https://user-images.githubusercontent.com/32251060/40094998-b1152954-587e-11e8-9bea-a8a9d7e455d9.png)
![browser](https://user-images.githubusercontent.com/32251060/40095006-b5eda938-587e-11e8-9c33-d2ffab48db88.PNG)

**Comment by DxCx** [comment]
yes, this is exactly it.. ^_^

**Comment by HackedGameMaker** [comment]
On I've figured out the duplication glitch but I've run into a problem while fixing it, if the creator sees this I'll let them know what I've discovered and hopefully we can solve the problem together. I'll still work on it alone to see if I forgot to add something, but I would still like to have the creator help me out since they know the source code better than I do.

**Comment by DxCx** [comment]
Do tell us more please @HackedGameMaker :)

**Comment by HackedGameMaker** [comment]
Alright hold on let me make a pull request to make things easier

**Comment by HackedGameMaker** [comment]
@DxCx I've made the pull request so you can see the issue I'm having.
