### ISSUE TITLE
9Anime Kodi Addon( i am new user to it)

### ISSUE THREAD

**Issue by zenakuadevent** [DxCx/plugin.video.9anime#31]
Anyone know how to install 9anime onto kodi using a firestick tv. i am about to get one and i want to know how to install it. i was reading how to install it and it says download the zip, but does that mean i have to use the downloader app to download it then install? because i use to seeing people using add source and this say download zip so that the part i am confused about @_@ . if anyone can give me a step by step or a tutorial link that would be great thanks!!!

**Comment by tinymovingparts** [comment]
download this zip file with downloader
https://github.com/DxCx/plugin.video.9anime/archive/master.zip
dont open just download and close
than install from zip in Kodi. It will be in: external storage -> Downloader
also it must be version Krypton if I'm not mistaken.

**Comment by zenakuadevent** [comment]
Thanks you sir or madame!
suck my firestick wont be here till  the 31st.  but thank you again for explaining it!

**Comment by DxCx** [comment]
hey @tinymovingparts thanks!
want to open a PR to update README.md with how to install on firestick?

**Comment by tinymovingparts** [comment]
@DxCx sure , I'll get on once I get home.

**Comment by DxCx** [comment]
cool thanks! =) this is not the first time i see questions about firestick and i don't have one :S

**Comment by tinymovingparts** [comment]
@DxCX its no problem, I think the initial step of installing the zip is what intimidates most firestick users since its the one step that is outside of Kodi and it involves knowing a little more about where files are stored in the stick. however I'm new to github and not sure how to open a PR. here is the step by step for you if you want to post it in the readme:

This step by step guide is for learning purposes only and demonstrates installing the plugin. It assumes that Kodi Krypton has already been installed on to the firestick. It also requires the app “Downloader” (published by AFTVnews) found in the amazon store.

1. Search for the app [Downloader] in the amazon app store.
2. download the app and open
3. once opened, enter in the URL https://github.com/DxCx/plugin.video.9anime/archive/master.zip
4. then click go. It will download the zip, once downloaded close out the app
5. Open up Kodi and click on add ons
6. scroll up to the icon of the package and click on it
7. scroll to “install from zip file”
8. scroll down to External Storage and open folder, then open downloader folder. Inside Downloader folder find the master.zip file.
9. Click on the zip file and the plugin will install. Finished

**Comment by DxCx** [comment]
thanks @tinymovingparts ,
i can just paste it myself but if you want to learn how to open a PR i'm totally in for helping you =)
this kind of a small PR you don't even have to open a console or pull the code you can do it straight from github?
are you into learning or i'll just place it myself?

**Comment by tinymovingparts** [comment]
@DxCx thanks, I could go for learning a thing or two. how does it work.

**Comment by roafhtun** [comment]
Thanks my fav

**Comment by roafhtun** [comment]
I think someone should host the files so it'll be easier to receive updates directly from kodi

**Comment by DxCx** [comment]
hmm alright @tinymovingparts,
so, basiclly, you want to open a the file you want to edit:
https://github.com/DxCx/plugin.video.9anime/blob/master/README.md
then press on 'edit this file' (top right)
now, you have 2 modes, Markdown and preview, and you can modify the file
finally on Commit changes, select you want to create a new branch
and then it should create a branch and open a PR window..

@roafhtun i don't have any repo myself or someone who's offered to host it..

**Comment by tinymovingparts** [comment]
@DxCx thanks, still a little confused I'll let you handle it.

**Comment by DxCx** [comment]
thanks @tinymovingparts 
just merged #33 :)
