### ISSUE TITLE
[Request] Autoplay

### ISSUE THREAD

**Issue by Crashdummyy** [DxCx/plugin.video.9anime#56]
First of all, Thanks a lot :) :)
I relly appreciate your work.

I did get here for Kissanime stopped working on Kodi ( Captchas :( )
Thanks to your work I can watch on my FireTV stick again.

Still I really love Kodis Autoplay Feature ( Play from here ), is there a way to implement automatic Hoster Selection in the next Release ?

PS: Partially I wouldn't Mind clicking, but the lists is sorted in descending order ( would need ascending order though )

**Comment by hoppler** [comment]
without refactoring of the code it wouldnt be convenient because sometimes a server is not working despite beeing listed. with autoplay you would currently always fail to play the file as it autoselects the displayed but not working server.

**Comment by DxCx** [comment]
@hoppler thanks for helping out 👍 
but @Crashdummyy im not sure i understand the request..
you want the plugin to auto select a source instead of showing a list?

**Comment by justin89h** [comment]
Pretty sure hoppler is on the right track with the autoplay. Might I suggest a "play using..." backup option in the context menu, similar to what Exodus has implemented? Their autoplay feature is well thought out and most users seem pretty happy with it, despite it failing to find a working source occasionally.

The "play from here" option Crashdummyy mentions is designed to automatically attempt to play the next episode after the selected one has finished. This would need the list in ascending order so that it doesn't play the episodes in reverse order :)

I would love to help out but I don't really have the time to start learning python from scratch at this stage :(

**Comment by hoppler** [comment]
@justin89h the "play usin..." option sounds good but without hacky coding it will not work and feel good. the processing pipeline of this plugin has to be reworked to handle retries if a stream failed to play. therefore it should cache all found sources (because of 503 for too many requests in a short period) and use them according to a predefined rule like: 1080p -> 720p and F1 -> F2 -> MyCloud -> Openload. all those things dont exist in the current code. so we need an python programmer with time and interest in a good product or take another working plugin (attention to the license beeing used) and patch 9anime into it.

**Comment by justin89h** [comment]
>   The Unofficial KissAnime Plugin, aka UKAP - a plugin for Kodi
>    Copyright (C) 2016 dat1guy
>
>    This file is part of UKAP.
>
>    UKAP is free software: you can redistribute it and/or modify
>    it under the terms of the GNU General Public License as published by
>    the Free Software Foundation, either version 3 of the License, or
>    (at your option) any later version.
>
>    UKAP is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.
>
>    You should have received a copy of the GNU General Public License
>    along with UKAP.  If not, see <http://www.gnu.org/licenses/>


This is in the head of the file that contains what looks like all the functions required to handle retries and quality settings for autoplay. Not an expert of licensing but does this give us freedom to use it? I'll have a muck with it tonight but will more then likely not achieve anything. If the licensing allows and you're interested I will upload the files somewhere.

**Comment by hoppler** [comment]
@justin89h looked into the code of the kissanime plugin and its a one-file mess^^

**Comment by justin89h** [comment]
Yep, looks like I'll have a lot more luck figuring out how this plugin works then the UKAP one. Way out of my depth but at least I should be able to get some idea of how it's put together and how difficult it is to implement things so at the very least I can offer slightly more educated ideas and error reporting.

**Comment by Crashdummyy** [comment]
@DxCx 
I thought that maybe there is a way to set a preferred quality and make the Resolver automatically pick that one up. Anyway autoplay itself ( play from here ) works.

**Comment by Crashdummyy** [comment]
@hoppler 
How about something like that ?
https://github.com/xStream-Kodi/plugin.video.xstream/blob/nightly/resources/lib/gui/hoster.py#L308

**Comment by hoppler** [comment]
@Crashdummyy please ask @DxCx for those changes as i dont intend to refactor this project. im merely supplying fixes if the sources fail to pass

**Comment by DxCx** [comment]
Hey guys :)
At the moment im in a hell of a pressure in life, but this feature sounds cool.
Im trying to keep the plugin as much functional as possible and to be honest @githubus11 & @hoppler are helping me alot with that..
If no one will pick it up till i have some free time ill do it for sure :)

**Comment by justin89h** [comment]
@Crashdummyy
Take a look at the fork I have created off of hoppler's if you like
https://github.com/justin89h/plugin.video.9anime

I have added some settings that can be used to automatically play a particular server at best or worst resolution (pick based on your net performance)

@DxCx
My python skills are pathetic, so the code I have added probably doesn't meet any kind of best practice. It does work though. As it's based off of hoppler's fork, once you have added his fixes in for MyCloud I can either work out how to do a pull request if you like or you and the other developers can just use it for ideas and probably implement something in a lot better way then I did :)

**Comment by DxCx** [comment]
@justin89h MyCloud is merged if you want to give it a try,
i don't mind to give you CR notes so you can learn and gain python experience =)

**Comment by DxCx** [comment]
Released in version 0.0.12, you should get it via auto update.
enjoy and thanks for @justin89h

**Comment by Crashdummyy** [comment]
Thanks for your hard work :+1: 
Now I can safely pass out while watching Anime :)
